services:
  db:
    image: postgres:latest
    container_name: pdf_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pdf_db
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pdf_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
